### ISSUE TITLE
On the generation of the QuaDRiGa channel

### ISSUE THREAD

**Issue by STARainZ** [benediktfesl/Diffusion_channel_est#1]
Hi Benedikt,
﻿
Thanks for the excellent work! 
﻿
Would you please kindly release the code for generating the QuaDRiGa channel? I have used my own implementation via the QuaDRiGa toolbox for generating the channel. However, I found that sometimes the LMMSE estimator based on the global sample covariance matrix (using about $10^5$ samples) performed pretty well, and the Diffusion model-based approach can hardly beat it.  So, I'm wondering how you generate the channel in the released dataset (I have tried your dataset and found that the Diffusion model outperforms LMMSE).
﻿
Thank you in advance.

**Comment by benediktfesl** [comment]
Hi Xingyu Zhou,

thanks for the interest in our work.

We have created the QuaDRiGa data using the examples in the [documentation](https://quadriga-channel-model.de/). In partuicular, we have used the _3GPP_38.901_UMa_LOS_ scenario. From my experience, having a different scenario with NLOS channels leads to a less-structured wireless channel distribution, and the Gaussian approximation of the LMMSE might already be fairly accurate, leaving not much room for improvement of a generative model-aided estimator. 

If you have any further questions or want to discuss something, you can also reach me via email: [benedikt.fesl@tum.de](mailto:benedikt.fesl@tum.de).

I hope this helps!

Best regards,
Benedikt

**Comment by STARainZ** [comment]
Hi Benedikt,

Thanks for the prompt reply and suggestions.

I have just tried the _3GPP_38.901_UMa_LOS scenario_. However, the results are similar to that of the NLOS channels for my case. I guess that this can be attributed to the configuration of the MT's location when generating the channel dataset. I think you simulate a multiple-antenna MT, maybe I'm wrong. If so, for the generation of the channels, how do you control the MT's location? Is it fixed, moving, or randomly dropped? If you randomly drop the MT, I'm wondering how many random drops of the MT's location you use in your implementation.

Thank you in advance.

Best regards,
Xingyu

**Comment by benediktfesl** [comment]
Dear Xingyu,

yes, we have simulated a massive MIMO scenario where the MTs have multiple antennas. 
The MTs are placed randomly in a 120° sector with distances ranging from 35m-500m from the base station. We do not consider time evolution of moving users.
Please also see the preprint of the referenced [paper](https://arxiv.org/abs/2403.03545) for details about the simulation setup and the chosen scenario.

Best regards,
Benedikt

**Comment by STARainZ** [comment]
Dear Benedikt,

I have one more question: For each channel realization (the 64 $\times$ 16 MIMO channel matrix), is the MT fixed or with random locations? In other words, I'm curious about whether the 12,0000 channel realizations in "120000UEs_500m_1x64BS_1x16MS_1carr_1symb_diff=0_quadriga_LOS.mat" have the same MT location or not?

Best regards,
Xingyu

**Comment by benediktfesl** [comment]
Dear Xingyu,

as stated before, each channel realization in the dataset belongs to a different, randomly sampled, location in the BS cell. This is important as we aim to learn the environment-specific data distribution. 

Best regards,
Benedikt

**Comment by STARainZ** [comment]
Dear Benedikt,

I think maybe the problem is coming from the removal of the effective channel gain. Previously I performed a normalization for the entire channel dataset as in https://github.com/utcsilab/score-based-channels/blob/9bc4ed98364ea14c7bf879b8fa2c48b7225edc8f/loaders.py#L47, and yesterday I found this method made the channel gain of different realizations vary significantly since the MT's locations are random. So I changed to perform normalization for each channel realization to ensure the average power of each element in a MIMO channel matrix is 1 (I'm not sure if this is your approach in the paper), and with this approach, the problem is resolved seemingly.

Best regards,
Xingyu

**Comment by benediktfesl** [comment]
Dear Xingyu,

we removed the effective path gain of each channel according to the Quadriga documentation (see Section 3.7). Afterward, we pre-processed the channels such that each entry has variance one. Other than that, we did no further realization-specific normalization.

Best regards,
Benedikt
