### ISSUE TITLE
research_algorithms

### ISSUE THREAD

**Issue by oneenooo** [benediktfesl/Diffusion_channel_est#2]
Thank you very much for your excellent work! After downloading your code, I did not find any files or folders for "research_algorithms". An error occurred while running these two lines of code "from research_algorithms.SCM3GPP.SCMMulti import SCMMulti
from research_algorithms.SCM3GPP.SCMMulti_MIMO import SCMMulti as SCMMulti_MIMO ". Where do I need to download them myself or did you forget to provide them? If you have this code, could you please provide it for me to reproduce the results of your paper. Thank you!

**Comment by benediktfesl** [comment]
Thanks for reporting this issue, this was an obsolete dependency. I just updated the code to fix this issue. The data for reproducing the results from the paper can be found in the sharefolder as linked in the description.

Best regards,
Benedikt
