### ISSUE TITLE
Missing data set files

### ISSUE THREAD

**Issue by ykykle** [benediktfesl/Diffusion_channel_est#3]
Hi Benedikt, thanks for your excellent work! I wonder if there should have a "3gpp_path=3_dimrx=64_dimtx=16_samp=100000_train.npy" file in bin, I encountered a missing data error when I tried to run the code.  Please forgive me if I used my words poorly.  Looking forward to your reply. Thanks in advance!

**Comment by benediktfesl** [comment]
Hi Qzyoo,

have you downloaded the data from the shared folder and added it to ./bin as described in the readme?

Best regards

**Comment by ykykle** [comment]
Hi Benedikt, I have downloaded the data you shared, but there is no "3gpp_path=3_dimrx=64_dimtx=16_samp=100000_train.npy" in bin. Is it possible that you missed uploading this file? Thanks for your reply.
![Snipaste_2024-12-10_10-33-06](https://github.com/user-attachments/assets/76f23e94-f968-40d6-864d-c882a38c94c9)

**Comment by benediktfesl** [comment]
I just checked again and the file is in the shared folder. Please try downloading the shared data again, maybe your previous download was corrupted.

Best regards

**Comment by ykykle** [comment]
Hi Benedikt,

I apologize for my rudeness, it's totally my mistake. Thanks for your timely reply! Again, thanks for your excellent work!

Wish you all the best
